blink:
    app-info:
        app_version: '6.0.15 (8608) #b2ca762c'
        client_name: Blink Web Portal
        client_type: ios
        device_identifier: iPhone12,3
        notification_key: 3d0aaf42e8578768b0f0ac5686425206be8ef777adbdec65302b5a47bde53522
        os_version: 14.0
        unique_id: 2f9d04bc-1de9-4e95-d793-b55d57291337
    app-headers:
        accept-language: en-US
        app-build: IOS_8608
        locale: en_US
        user-agent: Blink/8608 CFNetwork/1195.4 Darwin/20.0.0
    serverUrl: immedia-semi.com
logging:
    level:
        root: INFO
server:
    compression:
        enabled: true
        mime-types: text/html,text/css,application/javascript,application/json
    http2:
        enabled: true
spring:
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
uiBuildPath: /Users/adobre/Projects/Blink Web UI [FE]/dist/
